language: java
jdk:
- openjdk8
sudo: true
addons:
  mariadb: '10.1'
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq sphinxsearch
- ./install/install.sh
before_script:
- mysql -uroot < srvlog-sql/db/create_srvlog_db.sql
- sudo cp srvlog-it/travis/mariadb/my.cnf /etc/mysql/my.cnf
- sudo service mysql restart
script:
- mvn clean test -Pintegration-test
- mvn jacoco:report
- mvn sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=vzarubin-github -Dsonar.login=${SONAR_TOKEN}
