language: java
jdk:
- oraclejdk8
sudo: true
addons:
  mariadb: '10.0'
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq sphinxsearch
- ./install/install.sh
before_script:
- mysql -uroot < srvlog-sql/db/create_srvlog_db.sql
- sudo cp srlog-it/travis/mariadb/my.cnf /etc/mysql/my.cnf
- sudo service mysql restart
script: mvn clean install -Pintegration-test
